In [1]:
import json
import pandas as pd
import numpy as np

In [3]:
data_file = open("C:/Users/Sharon/datacode/Class-Projects/ATL-Foodie-heck yea/SourceData/yelp_academic_dataset_review.json", encoding='utf8') 
data = []
for line in data_file:
    data.append(json.loads(line))
df = pd.DataFrame(data)
data_file.close()

In [4]:
df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,1,"{'RestaurantsTableService': 'True', 'WiFi': 'u...","Gastropubs, Food, Beer Gardens, Restaurants, B...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'..."
1,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ..."
2,bvN78flM8NLprQ1a1y5dRg,The Reclaimory,4720 Hawthorne Ave,Portland,OR,97214,45.511907,-122.613693,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Antiques, Fashion, Used, Vintage & Consignment...","{'Thursday': '11:0-18:0', 'Friday': '11:0-18:0..."
3,oaepsyvc0J17qwi8cfrOWg,Great Clips,2566 Enterprise Rd,Orange City,FL,32763,28.914482,-81.295979,3.0,8,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Beauty & Spas, Hair Salons",None
4,PE9uqAjdw0E4-8mjGl3wVA,Crossfit Terminus,1046 Memorial Dr SE,Atlanta,GA,30316,33.747027,-84.353424,4.0,14,1,"{'GoodForKids': 'False', 'BusinessParking': '{...","Gyms, Active Life, Interval Training Gyms, Fit...","{'Monday': '16:0-19:0', 'Tuesday': '16:0-19:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160580,D2mHoIDXx9N8mS1pGoKV9Q,Eleven Oaks Realty,,Austin,TX,78701,30.272921,-97.744386,4.0,8,1,None,"Real Estate, Real Estate Services, Home Servic...","{'Monday': '9:0-19:0', 'Tuesday': '9:0-19:0', ..."
160581,bQX-kwVTyZgcdZGEPzce6Q,Webb's Honey,21777 State Rd 520,Orlando,FL,32833,28.499836,-81.047478,4.5,18,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsPri...","Health Markets, Food, Specialty Food, Grocery","{'Monday': '10:0-18:0', 'Tuesday': '10:0-18:0'..."
160582,wvFZ06nmPmQ2-IVoPqVYLA,Painting with a Twist,2164 S Chickasaw Trl,Orlando,FL,32825,28.511615,-81.270020,5.0,8,0,"{'DogsAllowed': 'False', 'ByAppointmentOnly': ...","Arts & Entertainment, Paint & Sip, Art Classes...","{'Monday': '0:0-0:0', 'Wednesday': '12:0-17:0'..."
160583,GB75wPibj3IjNauaoCxyGA,Havana Cafe,910 NW 14th St,Portland,OR,97209,45.529647,-122.685153,4.0,10,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsDel...","Cuban, Sandwiches, Restaurants, Cafes",None
160584,ngmLL5Y5OT-bYHKU0kKrYA,Zora Grille,1370 E Altamonte Dr,Altamonte Springs,FL,32701,28.663047,-81.346728,4.5,82,0,"{'RestaurantsReservations': 'True', 'OutdoorSe...","Restaurants, Middle Eastern, Mediterranean, Pe...","{'Tuesday': '17:0-21:0', 'Wednesday': '17:0-21..."

In [59]:
df.isnull().sum()

review_id      0
user_id        0
business_id    0
stars          0
useful         0
funny          0
cool           0
text           0
date           0
dtype: int64

In [60]:
atl_restaurant_df=pd.read_csv("C:/Users/Sharon/datacode/Class-Projects/ATL-Foodie-heck yea/Resources/yelp_atl_restaurants_csv.csv")
atl_restaurant_df.head()

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
1,86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
2,105,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340,33.896641,-84.280918,3.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Business...","Restaurants, Chinese",NaN
3,147,bP6goJODwRnM3AVy45Kn9w,Papi's Cuban & Caribbean Grill,216 Ponce De Leon Ave NE,Atlanta,GA,30308,33.772758,-84.380375,4.0,1001,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Caribbean, Cuban, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
4,165,xSLdQjPgMhBrNIEtUgdWUA,Colossus Pizza,4369 Hugh Howell Rd,Tucker,GA,30084,33.850775,-84.209299,4.0,58,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Nightlife, Pizza, Sandwiches, Mediterranean, G...","{'Tuesday': '11:30-21:0', 'Wednesday': '11:30-..."

In [61]:
atl_restaurant_review_df=pd.merge(atl_restaurant_df,df, on="business_id", how ="left")
atl_restaurant_review_df

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,stars_x,...,categories,hours,review_id,user_id,stars_y,useful,funny,cool,text,date
0,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",KM7ZEiGlyX63IFpOIjqrSA,7PiRdxYF-Uvzn2fHqdtU1Q,5.0,0,0,0,Wow! After perusing the restaurants at the ma...,2018-01-13 22:16:22
1,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",dKIxCfc59WdoBIIDOJ_yKg,oMCunvPAP2olnSMXCi5DWg,2.0,1,0,0,"Located in Lenox Square mall, I wasn't particu...",2015-02-21 08:27:33
2,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",7Y7lieOUYLzuH92lLejhtw,HHWtSl2bZMCFuvf9S-TNdg,2.0,0,0,0,Nah dude \nCustomer service - nope \n\nSeems s...,2018-02-10 22:30:34
3,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",0xcD-hAa2VzjVxj8y-uirg,N14D0hXbrQBiaaXX6NPqCw,2.0,0,0,0,I've always liked the classic gyro combo at gr...,2017-12-01 16:48:20
4,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",19cgAjk4S0oNIPOHnLbG9Q,CqcyxQOuA5u8DDZgH4loHg,5.0,0,0,0,The food is amazing they have one of the best ...,2016-10-13 18:23:45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477664,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",xFc-MyNqtINzBhJebZwpHw,NJORUxvEopLz8eOL2SiZAA,5.0,0,0,0,Forget what literally anyone on here is crying...,2020-12-08 05:56:49
477665,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",yo3HeA3H1OKRLFIO9Cqhew,ctHUzB-gY1oL8Q-WC6ZAuA,3.0,0,0,1,I really do appreciate the fact that this rest...,2020-07-08 08:54:44
477666,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",Dl00DX41j-qkkLWgxbKmDg,0WoagQUCpDFgtZfOjy-lpw,5.0,1,0,0,This is a 24hr MEXICAN SPOT. Open for Drive-th...,2020-09-22 17:10:21
477667,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",CgrQGK5xlhjwclppfFbNIQ,xl5idW5JOPBHeys2KLGSKA,5.0,0,0,0,They always have a line but it moves very quic...,2020-12-30 19:44:35
477668,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",I0pX4rYvtq4WCGVigfhqmQ,5Zc8u7XDZGz1UaCc_kZfcA,3.0,0,1,1,When you come here your coming for one thing!!...,2020-05-21 14:24:34

In [86]:
clean_atl_restaurant_review_df = atl_restaurant_review_df.drop(['Unnamed: 0'], axis=1).dropna(how='any')
clean_atl_restaurant_review_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars_x,review_count,...,categories,hours,review_id,user_id,stars_y,useful,funny,cool,text,date
0,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",KM7ZEiGlyX63IFpOIjqrSA,7PiRdxYF-Uvzn2fHqdtU1Q,5.0,0,0,0,Wow! After perusing the restaurants at the ma...,2018-01-13 22:16:22
1,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",dKIxCfc59WdoBIIDOJ_yKg,oMCunvPAP2olnSMXCi5DWg,2.0,1,0,0,"Located in Lenox Square mall, I wasn't particu...",2015-02-21 08:27:33
2,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",7Y7lieOUYLzuH92lLejhtw,HHWtSl2bZMCFuvf9S-TNdg,2.0,0,0,0,Nah dude \nCustomer service - nope \n\nSeems s...,2018-02-10 22:30:34
3,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",0xcD-hAa2VzjVxj8y-uirg,N14D0hXbrQBiaaXX6NPqCw,2.0,0,0,0,I've always liked the classic gyro combo at gr...,2017-12-01 16:48:20
4,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",19cgAjk4S0oNIPOHnLbG9Q,CqcyxQOuA5u8DDZgH4loHg,5.0,0,0,0,The food is amazing they have one of the best ...,2016-10-13 18:23:45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477664,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",xFc-MyNqtINzBhJebZwpHw,NJORUxvEopLz8eOL2SiZAA,5.0,0,0,0,Forget what literally anyone on here is crying...,2020-12-08 05:56:49
477665,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",yo3HeA3H1OKRLFIO9Cqhew,ctHUzB-gY1oL8Q-WC6ZAuA,3.0,0,0,1,I really do appreciate the fact that this rest...,2020-07-08 08:54:44
477666,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",Dl00DX41j-qkkLWgxbKmDg,0WoagQUCpDFgtZfOjy-lpw,5.0,1,0,0,This is a 24hr MEXICAN SPOT. Open for Drive-th...,2020-09-22 17:10:21
477667,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",CgrQGK5xlhjwclppfFbNIQ,xl5idW5JOPBHeys2KLGSKA,5.0,0,0,0,They always have a line but it moves very quic...,2020-12-30 19:44:35
477668,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",I0pX4rYvtq4WCGVigfhqmQ,5Zc8u7XDZGz1UaCc_kZfcA,3.0,0,1,1,When you come here your coming for one thing!!...,2020-05-21 14:24:34

In [89]:
clean_atl_restaurant_review_df.head(2)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars_x,review_count,...,categories,hours,review_id,user_id,stars_y,useful,funny,cool,text,date
0,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",KM7ZEiGlyX63IFpOIjqrSA,7PiRdxYF-Uvzn2fHqdtU1Q,5.0,0,0,0,Wow! After perusing the restaurants at the ma...,2018-01-13 22:16:22
1,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",dKIxCfc59WdoBIIDOJ_yKg,oMCunvPAP2olnSMXCi5DWg,2.0,1,0,0,"Located in Lenox Square mall, I wasn't particu...",2015-02-21 08:27:33

In [87]:
clean_atl_restaurant_review_df.isnull().sum()

business_id     0
name            0
address         0
city            0
state           0
postal_code     0
latitude        0
longitude       0
stars_x         0
review_count    0
is_open         0
attributes      0
categories      0
hours           0
review_id       0
user_id         0
stars_y         0
useful          0
funny           0
cool            0
text            0
date            0
dtype: int64

In [90]:
clean_atl_restaurant_review_df.drop(clean_atl_restaurant_review_df[clean_atl_restaurant_review_df['is_open']==0].index,inplace=True)
clean_atl_restaurant_review_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars_x,review_count,...,categories,hours,review_id,user_id,stars_y,useful,funny,cool,text,date
0,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",KM7ZEiGlyX63IFpOIjqrSA,7PiRdxYF-Uvzn2fHqdtU1Q,5.0,0,0,0,Wow! After perusing the restaurants at the ma...,2018-01-13 22:16:22
1,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",dKIxCfc59WdoBIIDOJ_yKg,oMCunvPAP2olnSMXCi5DWg,2.0,1,0,0,"Located in Lenox Square mall, I wasn't particu...",2015-02-21 08:27:33
2,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",7Y7lieOUYLzuH92lLejhtw,HHWtSl2bZMCFuvf9S-TNdg,2.0,0,0,0,Nah dude \nCustomer service - nope \n\nSeems s...,2018-02-10 22:30:34
3,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",0xcD-hAa2VzjVxj8y-uirg,N14D0hXbrQBiaaXX6NPqCw,2.0,0,0,0,I've always liked the classic gyro combo at gr...,2017-12-01 16:48:20
4,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",19cgAjk4S0oNIPOHnLbG9Q,CqcyxQOuA5u8DDZgH4loHg,5.0,0,0,0,The food is amazing they have one of the best ...,2016-10-13 18:23:45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477664,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",xFc-MyNqtINzBhJebZwpHw,NJORUxvEopLz8eOL2SiZAA,5.0,0,0,0,Forget what literally anyone on here is crying...,2020-12-08 05:56:49
477665,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",yo3HeA3H1OKRLFIO9Cqhew,ctHUzB-gY1oL8Q-WC6ZAuA,3.0,0,0,1,I really do appreciate the fact that this rest...,2020-07-08 08:54:44
477666,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",Dl00DX41j-qkkLWgxbKmDg,0WoagQUCpDFgtZfOjy-lpw,5.0,1,0,0,This is a 24hr MEXICAN SPOT. Open for Drive-th...,2020-09-22 17:10:21
477667,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",CgrQGK5xlhjwclppfFbNIQ,xl5idW5JOPBHeys2KLGSKA,5.0,0,0,0,They always have a line but it moves very quic...,2020-12-30 19:44:35
477668,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",I0pX4rYvtq4WCGVigfhqmQ,5Zc8u7XDZGz1UaCc_kZfcA,3.0,0,1,1,When you come here your coming for one thing!!...,2020-05-21 14:24:34

In [88]:
clean_atl_restaurant_review_df.describe()

,postal_code,latitude,longitude,stars_x,review_count,is_open,stars_y,useful,funny,cool
count,465047.000000,465047.000000,465047.000000,465047.000000,465047.000000,465047.000000,465047.000000,465047.000000,465047.000000,465047.000000
mean,30293.292964,33.810447,-84.348436,3.757202,563.883014,0.793133,3.754257,0.956422,0.354695,0.467344
std,80.314952,0.051095,0.038895,0.535368,679.039530,0.405060,1.339280,2.805317,1.809800,2.205886
min,30002.000000,33.639574,-84.457466,1.000000,5.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,30307.000000,33.772200,-84.379998,3.500000,174.000000,1.000000,3.000000,0.000000,0.000000,0.000000
50%,30309.000000,33.787963,-84.362742,4.000000,358.000000,1.000000,4.000000,0.000000,0.000000,0.000000
75%,30326.000000,33.846614,-84.327221,4.000000,654.000000,1.000000,5.000000,1.000000,0.000000,0.000000
max,30360.000000,33.949866,-84.200206,5.000000,3861.000000,1.000000,5.000000,411.000000,259.000000,371.000000

In [91]:
clean_atl_restaurant_review_df2=clean_atl_restaurant_review_df.rename(columns={'stars_x':'stars(avg)','stars_y':'stars(review)'}).drop(['is_open'],axis=1)
clean_atl_restaurant_review_df2

,business_id,name,address,city,state,postal_code,latitude,longitude,stars(avg),review_count,...,categories,hours,review_id,user_id,stars(review),useful,funny,cool,text,date
0,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",KM7ZEiGlyX63IFpOIjqrSA,7PiRdxYF-Uvzn2fHqdtU1Q,5.0,0,0,0,Wow! After perusing the restaurants at the ma...,2018-01-13 22:16:22
1,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",dKIxCfc59WdoBIIDOJ_yKg,oMCunvPAP2olnSMXCi5DWg,2.0,1,0,0,"Located in Lenox Square mall, I wasn't particu...",2015-02-21 08:27:33
2,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",7Y7lieOUYLzuH92lLejhtw,HHWtSl2bZMCFuvf9S-TNdg,2.0,0,0,0,Nah dude \nCustomer service - nope \n\nSeems s...,2018-02-10 22:30:34
3,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",0xcD-hAa2VzjVxj8y-uirg,N14D0hXbrQBiaaXX6NPqCw,2.0,0,0,0,I've always liked the classic gyro combo at gr...,2017-12-01 16:48:20
4,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,...,"Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",19cgAjk4S0oNIPOHnLbG9Q,CqcyxQOuA5u8DDZgH4loHg,5.0,0,0,0,The food is amazing they have one of the best ...,2016-10-13 18:23:45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477664,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",xFc-MyNqtINzBhJebZwpHw,NJORUxvEopLz8eOL2SiZAA,5.0,0,0,0,Forget what literally anyone on here is crying...,2020-12-08 05:56:49
477665,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",yo3HeA3H1OKRLFIO9Cqhew,ctHUzB-gY1oL8Q-WC6ZAuA,3.0,0,0,1,I really do appreciate the fact that this rest...,2020-07-08 08:54:44
477666,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",Dl00DX41j-qkkLWgxbKmDg,0WoagQUCpDFgtZfOjy-lpw,5.0,1,0,0,This is a 24hr MEXICAN SPOT. Open for Drive-th...,2020-09-22 17:10:21
477667,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",CgrQGK5xlhjwclppfFbNIQ,xl5idW5JOPBHeys2KLGSKA,5.0,0,0,0,They always have a line but it moves very quic...,2020-12-30 19:44:35
477668,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,...,"Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",I0pX4rYvtq4WCGVigfhqmQ,5Zc8u7XDZGz1UaCc_kZfcA,3.0,0,1,1,When you come here your coming for one thing!!...,2020-05-21 14:24:34

In [96]:
final_atl_restaurant_review_df=clean_atl_restaurant_review_df2.sample(n=40000)
final_atl_restaurant_review_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars(avg),review_count,...,categories,hours,review_id,user_id,stars(review),useful,funny,cool,text,date
388551,dTsp-JNNA7u5F9WtxVBEug,Bistro Niko,3344 Peachtree Rd NE,Atlanta,GA,30326,33.846614,-84.368617,4.0,796,...,"Bars, Breakfast & Brunch, French, Restaurants,...","{'Monday': '11:30-21:0', 'Tuesday': '11:30-21:...",d0aHfu8rNARtLaWgoogG5g,n3tC1MJOOuO0bDlGOs90WA,5.0,0,0,0,"Excellent presentation, wonderful preparation,...",2018-05-02 00:54:47
332247,LcBV4SR2IYK970f2X-1flA,Farm Burger - Dunwoody,4514B Chamblee Dunwoody Rd,Dunwoody,GA,30338,33.922835,-84.315304,4.0,550,...,"Salad, Restaurants, Wine Bars, Bars, Burgers, ...","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'...",sm7tPS7IZvzyTayAjrwAuA,hVZa-5uQLhXbg2tVIvUrsA,4.0,0,0,0,I went here with my family to try somewhere ne...,2014-04-27 18:37:51
450177,4w3OTSAnGkpMUBellQKcsQ,MetroFresh,"931 Monroe Dr NE, Ste A 106",Atlanta,GA,30308,33.780277,-84.368312,4.0,301,...,"American (New), Restaurants, Salad, Breakfast ...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-19:0', '...",reDuMheUyTUnJoL6z0_XNg,CQBHEHzgLeyUhLoFpPLzUQ,4.0,0,0,0,"Love this place! GF options are awesome, but c...",2017-07-02 06:09:26
317217,xI56hTOOHsQfk-DZviOrxQ,The Original El Taco,1186 N Highland Ave NE,Atlanta,GA,30306,33.786997,-84.355746,4.0,440,...,"Tex-Mex, Mexican, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '17:0-20:30',...",L04d6HbufaNHDcmg2AgA3Q,PqzbSsrIwqorvm4xKqOB3g,5.0,2,0,0,My boyfriend and I hosted a group of 20 people...,2013-12-02 04:12:58
120950,eG-UO83g_5zDk70FIJbm2w,South City Kitchen Midtown,1144 Crescent Ave NE,Atlanta,GA,30309,33.785954,-84.384434,4.5,2618,...,"Restaurants, American (New), Southern, Breakfa...","{'Monday': '0:0-0:0', 'Tuesday': '17:0-21:0', ...",f-4-Yyd9tzTEOSWmGT5Qaw,11H1DX-F2FsWoN3rEZxSaQ,5.0,0,0,0,Just moved here from Chicago a few months ago ...,2015-08-25 12:27:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102211,rttvJkm9fTHmVQrsD6EA5A,Bo Bo Garden,5181 Buford Hwy NE,Doraville,GA,30340,33.893725,-84.283183,3.5,406,...,"Restaurants, Asian Fusion, Chinese","{'Monday': '11:30-21:0', 'Tuesday': '11:30-21:...",i6smNnE_-bH2HZgeSQQ-zA,U_EyCLmKxHcjBz1C-LXcCA,4.0,3,1,2,Last week I went to Bo Bo Garden for a birthda...,2012-05-10 05:45:37
389757,f2tTzO54v9FNUZaGbIXJFQ,Varasano's Pizzeria,2171 Peachtree Rd NE,Atlanta,GA,30309,33.813935,-84.391625,3.5,561,...,"Italian, Pizza, Restaurants","{'Monday': '17:30-22:0', 'Tuesday': '17:30-22:...",-G0dGOMN-n8AX5G9u0DA8g,6s6lN_pBaf0WZ-Pv-pYhdA,4.0,1,1,0,Came here for dinner with a large group and ha...,2011-04-13 20:16:02
245932,vdQLCK1Y--vI2Oq7Nfm0nw,The Big Ketch Saltwater Grill,3279 Roswell Rd NE,Atlanta,GA,30305,33.844712,-84.379519,3.5,508,...,"American (Traditional), Seafood, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '11:0-20:0', ...",ZrhON5hEFTEutkAoE92ftw,HFMdJdHRSBg1sgWDCx-eOA,4.0,1,0,0,"Excellent service. Ahi tuna, calamari and muss...",2016-11-22 20:59:40
137194,YIPzFF0CVgMCcly67VHgjw,bartaco,"299 N Highland Ave NW, Unit P",Atlanta,GA,30307,33.762498,-84.358631,4.0,641,...,"Desserts, Restaurants, Mexican, Bars, Nightlif...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-22:0', ...",ik_7n86_e8ldabEKR2SiNQ,MmNMrsWaQM5Y8qfEMD-74Q,3.0,3,0,1,I'll preface my review by saying that I'm not ...,2017-05-03 16:13:23
6741,MlXsuBBd9UwgBkQzrGDJqA,LanZhou Ramen,5231 Buford Hwy NE,Doraville,GA,30340,33.894818,-84.282134,4.0,471,...,"Chinese, Restaurants, Japanese, Ramen","{'Monday': '10:30-21:30', 'Tuesday': '10:30-21...",hoszCcn5JDxpnPco4ebTcA,7bckJkGsEM1yAXh9YwVd1Q,4.0,0,0,0,"As someone born and raised in NY, I know good ...",2020-08-23 06:06:16

In [97]:
final_atl_restaurant_review_df.to_json("yelp_atl_restaurant_reviews_json.json")

In [98]:
final_atl_restaurant_review_df.to_csv("yelp_atl_restaurant_reviews_csv.csv")