In [2]:
# Dependencies
import os
import json
import pandas as pd
import numpy as np
import matplotlib as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler

In [3]:
data_file = open("yelp_academic_dataset_business.json", encoding='utf8')
data = []
for line in data_file:
    data.append(json.loads(line))
df = pd.DataFrame(data)
data_file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'yelp_academic_dataset_business.json'

In [ ]:
df.isnull().sum()

In [ ]:
df.head()

In [ ]:
business_df = df[df['categories'].notna()]

In [ ]:
business_df.isnull().sum()

In [ ]:
business_df.head()

In [ ]:
business_df.describe()

In [ ]:
ga_df = business_df[(business_df['state'] == "GA")]
ga_df

In [ ]:
ga_df.categories.str.contains('Restaurant')

In [ ]:
restaurant_df=ga_df.loc[ga_df.categories.str.contains('Restaurant')]
restaurant_df

In [4]:
atl_restaurants_df = restaurant_df[(restaurant_df['postal_code'] == '30002') | (
    restaurant_df['postal_code'] == '30021') | (restaurant_df['postal_code'] == '30030') | (
        restaurant_df['postal_code'] == '30079') | (restaurant_df['postal_code'] == '30084') | (
            restaurant_df['postal_code'] == '30305') | (restaurant_df['postal_code'] == '30306') | (
                restaurant_df['postal_code'] == '30307') | (restaurant_df['postal_code'] == '30308') | (
                    restaurant_df['postal_code'] == '30309') | (restaurant_df['postal_code'] == '30312') | (
                        restaurant_df['postal_code'] == '30316') | (restaurant_df['postal_code'] == '30317') | (
                            restaurant_df['postal_code'] == '30319') | (restaurant_df['postal_code'] == '30324') | (
                                restaurant_df['postal_code'] == '30326') | (
                                    restaurant_df['postal_code'] == '30329') | (
                                        restaurant_df['postal_code'] == '30338') | (
                                            restaurant_df['postal_code'] == '30340') | (
                                                restaurant_df['postal_code'] == '30341') | (
                                                    restaurant_df['postal_code'] == '30342') | (
                                                        restaurant_df['postal_code'] == '30345') | (
                                                            restaurant_df['postal_code'] == '30360')]

NameError: name 'restaurant_df' is not defined

In [14]:
atl_restaurants_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': '{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
105,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340,33.896640,-84.280918,3.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Business...","Restaurants, Chinese",None
147,bP6goJODwRnM3AVy45Kn9w,Papi's Cuban & Caribbean Grill,216 Ponce De Leon Ave NE,Atlanta,GA,30308,33.772758,-84.380375,4.0,1001,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Caribbean, Cuban, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
165,xSLdQjPgMhBrNIEtUgdWUA,Colossus Pizza,4369 Hugh Howell Rd,Tucker,GA,30084,33.850775,-84.209299,4.0,58,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Nightlife, Pizza, Sandwiches, Mediterranean, G...","{'Tuesday': '11:30-21:0', 'Wednesday': '11:30-..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160375,fyBLsgCl04kzDyDvvntsig,Marco's Pita,752 Ponce De Leon Ave NE,Atlanta,GA,30306,33.774230,-84.362535,3.5,46,0,"{'RestaurantsPriceRange2': '1', 'RestaurantsRe...","Restaurants, Greek","{'Monday': '12:0-20:0', 'Tuesday': '12:0-20:0'..."
160390,N7luSQX9HJIYJzIdqzIEng,Vickery's Bar & Grill,1106 Crescent Ave NE,Atlanta,GA,30309,33.785008,-84.384517,3.5,47,0,"{'OutdoorSeating': 'True', 'RestaurantsReserva...","American (New), Southern, Restaurants","{'Monday': '11:30-2:0', 'Tuesday': '11:30-2:0'..."
160499,P6VbBg5uNhAaANcpwm2cVQ,Moe's Southwest Grill,863 Ponce De Leon Ave,Atlanta,GA,30306,33.773536,-84.359011,2.5,53,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Restaurants, Mexican, Tex-Mex","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
160522,OF1RGkYOeT2xxoi_Xnec7w,Emeril's Atlanta,"3500 Lenox Rd NE, Ste 100",Atlanta,GA,30326,33.852144,-84.365957,3.0,9,0,"{'RestaurantsAttire': ''dressy'', 'GoodForKids...","American (New), Restaurants, Cajun/Creole","{'Monday': '18:0-22:0', 'Tuesday': '18:0-22:0'..."
160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': 'u'no'', 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [15]:
atl_restaurants_df.reset_index()

,index,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
1,86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': '{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
2,105,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340,33.896640,-84.280918,3.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Business...","Restaurants, Chinese",None
3,147,bP6goJODwRnM3AVy45Kn9w,Papi's Cuban & Caribbean Grill,216 Ponce De Leon Ave NE,Atlanta,GA,30308,33.772758,-84.380375,4.0,1001,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Caribbean, Cuban, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
4,165,xSLdQjPgMhBrNIEtUgdWUA,Colossus Pizza,4369 Hugh Howell Rd,Tucker,GA,30084,33.850775,-84.209299,4.0,58,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Nightlife, Pizza, Sandwiches, Mediterranean, G...","{'Tuesday': '11:30-21:0', 'Wednesday': '11:30-..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3147,160375,fyBLsgCl04kzDyDvvntsig,Marco's Pita,752 Ponce De Leon Ave NE,Atlanta,GA,30306,33.774230,-84.362535,3.5,46,0,"{'RestaurantsPriceRange2': '1', 'RestaurantsRe...","Restaurants, Greek","{'Monday': '12:0-20:0', 'Tuesday': '12:0-20:0'..."
3148,160390,N7luSQX9HJIYJzIdqzIEng,Vickery's Bar & Grill,1106 Crescent Ave NE,Atlanta,GA,30309,33.785008,-84.384517,3.5,47,0,"{'OutdoorSeating': 'True', 'RestaurantsReserva...","American (New), Southern, Restaurants","{'Monday': '11:30-2:0', 'Tuesday': '11:30-2:0'..."
3149,160499,P6VbBg5uNhAaANcpwm2cVQ,Moe's Southwest Grill,863 Ponce De Leon Ave,Atlanta,GA,30306,33.773536,-84.359011,2.5,53,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Restaurants, Mexican, Tex-Mex","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
3150,160522,OF1RGkYOeT2xxoi_Xnec7w,Emeril's Atlanta,"3500 Lenox Rd NE, Ste 100",Atlanta,GA,30326,33.852144,-84.365957,3.0,9,0,"{'RestaurantsAttire': ''dressy'', 'GoodForKids...","American (New), Restaurants, Cajun/Creole","{'Monday': '18:0-22:0', 'Tuesday': '18:0-22:0'..."
3151,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': 'u'no'', 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [16]:
atl_restaurants_df.to_json("yelp_atl_restaurants.json")

In [18]:
atl_restaurants_df.to_csv("yelp_atl_restaurants_csv.csv")

### Read CSV back in to further clean data

In [21]:
atl_restaurants_df = pd.read_csv("../yelp_atl_restaurants_csv.csv")

In [22]:
categories_col_list = []
for index, row in atl_restaurants_df.iterrows():
    categories_col_list.append(row["categories"])

In [23]:
categories_dict = {}

for categories in categories_col_list:
    cat_list = categories.split(", ")
    for item in cat_list:
        if categories_dict.get(item, False):
            categories_dict[item] += 1
        else:
            categories_dict[item] = 1
            
remove_list = ["Restaurants","Food","Bars","Nightlife","Event Planning & Services","Coffee & Tea",
               "Caterers","Desserts","Cocktail Bars","Lounges","Wine Bars","Wine & Spirits","Beer",
               "Sports Bars", "Ice Cream & Frozen Yogurt", "Venues & Event Spaces", "Hookah Bars",
               "Beer Bar", "Shopping", "Food Delivery Services", "Food Stands", "Gluten-Free", "Arts & Entertainment",
               'Juice Bars & Smoothies', "Grocery", "Food Court", "Automotive", "Convenience Stores",
               "Dance Clubs", "Breweries", "Local Flavor", "Bubble Tea", "Dive Bars"]

for item in remove_list:
    categories_dict.pop(item)
            
new_categories = []

for key, value in categories_dict.items():
    if value > 60:
        new_categories.append(key)
        
new_categories

['Sandwiches',
 'Bakeries',
 'Chinese',
 'Pizza',
 'Mediterranean',
 'Italian',
 'Southern',
 'Mexican',
 'Tex-Mex',
 'Fast Food',
 'Burgers',
 'Pubs',
 'American (Traditional)',
 'Korean',
 'Barbeque',
 'American (New)',
 'Seafood',
 'Asian Fusion',
 'Specialty Food',
 'Cafes',
 'Breakfast & Brunch',
 'Chicken Wings',
 'Japanese',
 'Thai',
 'Sushi Bars',
 'Steakhouses',
 'Soup',
 'Vietnamese',
 'Vegetarian',
 'Salad',
 'Delis',
 'Diners']

In [30]:
categories_df = pd.DataFrame({"Category": new_categories})
categories_df.to_csv("../categories.csv")
categories_df.to_json("../categories.json")

In [24]:
search_string = ""

for index, cat in enumerate(new_categories):
    if index == 0:
        search_string = cat
    else:
        search_string += f"|{cat}"
    
atl_restaurants_df["include"] = atl_restaurants_df["categories"].str.contains(search_string, regex=True)
atl_restaurants_df = atl_restaurants_df.loc[atl_restaurants_df["include"] == True, :]
del atl_restaurants_df["include"]
atl_restaurants_df

C:\Users\khutula\Anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
1,86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
2,105,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340,33.896640,-84.280918,3.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Business...","Restaurants, Chinese",NaN
4,165,xSLdQjPgMhBrNIEtUgdWUA,Colossus Pizza,4369 Hugh Howell Rd,Tucker,GA,30084,33.850775,-84.209299,4.0,58,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Nightlife, Pizza, Sandwiches, Mediterranean, G...","{'Tuesday': '11:30-21:0', 'Wednesday': '11:30-..."
5,182,zY12NvWB5QKNuLh9tbLEsA,Donnie's Country Cookin',"3300 Clairmont Rd NE, Ste A",Atlanta,GA,30329,33.855107,-84.313315,3.5,69,1,"{'Ambience': ""{'touristy': False, 'hipster': F...","Restaurants, Southern","{'Monday': '6:30-18:0', 'Tuesday': '6:30-18:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145,160305,Je0MNZ6Q9GnFmB5vS6UBhw,Sweet Hut Bakery & Cafe,"5150 Buford Hwy, Ste A-100",Doraville,GA,30340,33.893407,-84.284357,4.0,994,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Cafes, Bakeries, Restaurants, Food, Desserts","{'Monday': '9:0-21:0', 'Tuesday': '9:0-21:0', ..."
3146,160326,JVrYckDkbHXYK7RYyShDwA,Pot & Pan Restaurant,1865 Piedmont Ave NE,Atlanta,GA,30324,33.806718,-84.366219,3.5,19,0,"{'BusinessParking': ""{'garage': False, 'street...","Restaurants, American (Traditional), Southern","{'Tuesday': '6:0-14:0', 'Wednesday': '6:0-14:0..."
3148,160390,N7luSQX9HJIYJzIdqzIEng,Vickery's Bar & Grill,1106 Crescent Ave NE,Atlanta,GA,30309,33.785008,-84.384517,3.5,47,0,"{'OutdoorSeating': 'True', 'RestaurantsReserva...","American (New), Southern, Restaurants","{'Monday': '11:30-2:0', 'Tuesday': '11:30-2:0'..."
3149,160499,P6VbBg5uNhAaANcpwm2cVQ,Moe's Southwest Grill,863 Ponce De Leon Ave,Atlanta,GA,30306,33.773536,-84.359011,2.5,53,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Restaurants, Mexican, Tex-Mex","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
3151,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': ""u'no'"", 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [25]:
atl_restaurants_df.to_json("../yelp_atl_restaurants.json")

In [26]:
atl_restaurants_df.to_csv("../yelp_atl_restaurants_csv.csv")