In [2]:
import json
import pandas as pd

In [3]:
data_file = open("yelp_academic_dataset_tip.json", encoding='utf8')
data = []
for line in data_file:
    data.append(json.loads(line))
df = pd.DataFrame(data)
data_file.close()

In [4]:
df

,user_id,business_id,text,date,compliment_count
0,WCjg0jdHXMlwbqS9tZUx8Q,ENwBByjpoa5Gg7tKgxqwLg,Carne asada chips...,2011-07-22 19:07:35,0
1,42-Z02y9bABShAGZhuSzrQ,jKO4Og6ucdX2-YCTKQVYjg,Best happy hour from 3pm to 6pm! $1 off martin...,2014-09-10 07:33:29,0
2,5u7E3LYp_3eB8dLuUBazXQ,9Bto7mky640ocgezVKSfVg,"Nice people, skilled staff, clean location - b...",2013-12-13 23:23:41,0
3,wDWoMG5N9oI4DJ-p7z8EBg,XWFjKtRGZ9khRGtGg2ZvaA,"1/2-price bowling & the ""Very"" Old Fashion are...",2017-07-11 23:07:16,0
4,JmuFlorjjRshHTKzTwNtgg,mkrx0VhSMU3p3uhyJGCoWA,"Solid gold's. Great sauna. Great staff, too. E...",2016-11-30 08:46:36,0
...,...,...,...,...,...
1162114,OAf2rC_Btse6aRc9LCyApw,BYKjzEUv6RksSVm5yqGPDA,Perfect!,2020-05-30 20:01:46,0
1162115,bI5zqhhpU4SlW-5BN6M1uw,C2kDo2CFGP_0073dgMmZNw,Love these guys! My go to place,2015-07-18 17:21:40,0
1162116,vDMl9JwvkRNRVt_rjpQdZg,4CxF8c3MB7VAdY8zFb2cZQ,Overrated.,2020-07-23 04:02:10,0
1162117,iCc7UVah7zE1UwYPP3FcTg,IEHoGw0V5Lbdf4TJU58K0Q,"Best place for men, call for an appointment an...",2020-09-23 23:16:57,0
1162118,e9x-ZsbUPTVX3Xv_L9vSaw,Mt-6e5pSAft1f3sA8tTOsQ,"Fast, friendly, and quality service!! Would h...",2020-09-30 04:24:08,0

In [5]:
df.isnull().sum()

user_id             0
business_id         0
text                0
date                0
compliment_count    0
dtype: int64

In [12]:
atl_restaurant_df=pd.read_csv("Resources/yelp_atl_restaurants_csv.csv")
atl_restaurant_df.head()

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
1,86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
2,105,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340,33.896641,-84.280918,3.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Business...","Restaurants, Chinese",NaN
3,147,bP6goJODwRnM3AVy45Kn9w,Papi's Cuban & Caribbean Grill,216 Ponce De Leon Ave NE,Atlanta,GA,30308,33.772758,-84.380375,4.0,1001,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Caribbean, Cuban, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
4,165,xSLdQjPgMhBrNIEtUgdWUA,Colossus Pizza,4369 Hugh Howell Rd,Tucker,GA,30084,33.850775,-84.209299,4.0,58,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Nightlife, Pizza, Sandwiches, Mediterranean, G...","{'Tuesday': '11:30-21:0', 'Wednesday': '11:30-..."

In [14]:
atl_restaurant_df.drop(['Unnamed: 0'], axis=1)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
1,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
2,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340,33.896641,-84.280918,3.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Business...","Restaurants, Chinese",NaN
3,bP6goJODwRnM3AVy45Kn9w,Papi's Cuban & Caribbean Grill,216 Ponce De Leon Ave NE,Atlanta,GA,30308,33.772758,-84.380375,4.0,1001,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Caribbean, Cuban, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
4,xSLdQjPgMhBrNIEtUgdWUA,Colossus Pizza,4369 Hugh Howell Rd,Tucker,GA,30084,33.850775,-84.209299,4.0,58,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Nightlife, Pizza, Sandwiches, Mediterranean, G...","{'Tuesday': '11:30-21:0', 'Wednesday': '11:30-..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3147,fyBLsgCl04kzDyDvvntsig,Marco's Pita,752 Ponce De Leon Ave NE,Atlanta,GA,30306,33.774230,-84.362535,3.5,46,0,"{'RestaurantsPriceRange2': '1', 'RestaurantsRe...","Restaurants, Greek","{'Monday': '12:0-20:0', 'Tuesday': '12:0-20:0'..."
3148,N7luSQX9HJIYJzIdqzIEng,Vickery's Bar & Grill,1106 Crescent Ave NE,Atlanta,GA,30309,33.785008,-84.384517,3.5,47,0,"{'OutdoorSeating': 'True', 'RestaurantsReserva...","American (New), Southern, Restaurants","{'Monday': '11:30-2:0', 'Tuesday': '11:30-2:0'..."
3149,P6VbBg5uNhAaANcpwm2cVQ,Moe's Southwest Grill,863 Ponce De Leon Ave,Atlanta,GA,30306,33.773536,-84.359011,2.5,53,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Restaurants, Mexican, Tex-Mex","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
3150,OF1RGkYOeT2xxoi_Xnec7w,Emeril's Atlanta,"3500 Lenox Rd NE, Ste 100",Atlanta,GA,30326,33.852144,-84.365957,3.0,9,0,"{'RestaurantsAttire': ""'dressy'"", 'GoodForKids...","American (New), Restaurants, Cajun/Creole","{'Monday': '18:0-22:0', 'Tuesday': '18:0-22:0'..."
3151,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': ""u'no'"", 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [16]:
atl_restaurant_tip_df=pd.merge(atl_restaurant_df,df, on="business_id", how ="left")
atl_restaurant_tip_df

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,user_id,text,date,compliment_count
0,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",NaN,NaN,NaN,NaN
1,86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ...",ZM50t-6XKYJft-ScvipZmA,Just grabbed the last red velvet slice,2011-07-15 20:29:25,0.0
2,86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ...",j-oPMWv3mv4WT495yvjAxg,I like to get the caramel cupcakes instead of ...,2013-02-25 01:35:10,0.0
3,86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ...",xd1fn8QjMnM73eR_aBsaEQ,Buy yourself a little piece of heaven in the w...,2012-01-18 19:56:49,0.0
4,86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ...",Im4Z5DeKUmaQZos-B4x5vQ,My favorite guilty indulgence. Keep up the goo...,2016-10-27 23:54:45,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68308,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': ""u'no'"", 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",USThJe67XJ7Qtte5hv-5Lg,Check out my pictures.,2020-01-07 09:01:25,0.0
68309,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': ""u'no'"", 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",6tMNrv6k61IiHbTGjj6kuQ,Food was just average. No flavor or season.,2019-06-18 20:50:24,0.0
68310,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': ""u'no'"", 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",Tl6mmsHbDNQWqQ1KBfAwuA,Food and margs are great,2019-12-20 01:16:24,0.0
68311,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': ""u'no'"", 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",xrEuoOcuJjkXZvDtIGQtPg,They have roaches .,2016-04-25 17:56:38,0.0
68312,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': ""u'no'"", 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",fsYSGTdvgVBbrO1Jy4TIjA,Just as fast as Taco Bell. But a step-up from ...,2018-07-06 03:35:57,0.0

In [25]:
# atl_restaurant_tip_df = atl_restaurant_tip_df.drop(['Unnamed: 0'], axis=1)
atl_restaurant_tip_df.head(2)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,user_id,text,date,compliment_count
0,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ...",NaN,NaN,NaN,NaN
1,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ...",ZM50t-6XKYJft-ScvipZmA,Just grabbed the last red velvet slice,2011-07-15 20:29:25,0.0

In [27]:
atl_restaurant_tip_df.to_json("yelp_atl_restaurant_tips_json.json")

In [28]:
atl_restaurant_tip_df.to_csv("yelp_atl_restaurant_tips_csv.csv", index=False)