In [33]:
# Dependencies
import os
import json
import pandas as pd
import numpy as np
import matplotlib as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler

In [4]:
data_file = open("C:/Users/Sharon/datacode/Class-Projects/ATL-Foodie/static/Resources/OGDatasets/yelp_academic_dataset_business.json", encoding='utf8')
data = []
for line in data_file:
    data.append(json.loads(line))
df = pd.DataFrame(data)
data_file.close()

In [5]:
df.isnull().sum()

business_id         0
name                0
address             0
city                0
state               0
postal_code         0
latitude            0
longitude           0
stars               0
review_count        0
is_open             0
attributes      14992
categories        115
hours           27341
dtype: int64

In [6]:
df.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,1,"{'RestaurantsTableService': 'True', 'WiFi': 'u...","Gastropubs, Food, Beer Gardens, Restaurants, B...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'..."
1,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ..."
2,bvN78flM8NLprQ1a1y5dRg,The Reclaimory,4720 Hawthorne Ave,Portland,OR,97214,45.511907,-122.613693,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Antiques, Fashion, Used, Vintage & Consignment...","{'Thursday': '11:0-18:0', 'Friday': '11:0-18:0..."
3,oaepsyvc0J17qwi8cfrOWg,Great Clips,2566 Enterprise Rd,Orange City,FL,32763,28.914482,-81.295979,3.0,8,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Beauty & Spas, Hair Salons",None
4,PE9uqAjdw0E4-8mjGl3wVA,Crossfit Terminus,1046 Memorial Dr SE,Atlanta,GA,30316,33.747027,-84.353424,4.0,14,1,"{'GoodForKids': 'False', 'BusinessParking': '{...","Gyms, Active Life, Interval Training Gyms, Fit...","{'Monday': '16:0-19:0', 'Tuesday': '16:0-19:0'..."

In [7]:
business_df = df[df['categories'].notna()]

In [8]:
business_df.isnull().sum()

business_id         0
name                0
address             0
city                0
state               0
postal_code         0
latitude            0
longitude           0
stars               0
review_count        0
is_open             0
attributes      14879
categories          0
hours           27229
dtype: int64

In [9]:
business_df.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,1,"{'RestaurantsTableService': 'True', 'WiFi': 'u...","Gastropubs, Food, Beer Gardens, Restaurants, B...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'..."
1,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ..."
2,bvN78flM8NLprQ1a1y5dRg,The Reclaimory,4720 Hawthorne Ave,Portland,OR,97214,45.511907,-122.613693,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Antiques, Fashion, Used, Vintage & Consignment...","{'Thursday': '11:0-18:0', 'Friday': '11:0-18:0..."
3,oaepsyvc0J17qwi8cfrOWg,Great Clips,2566 Enterprise Rd,Orange City,FL,32763,28.914482,-81.295979,3.0,8,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Beauty & Spas, Hair Salons",None
4,PE9uqAjdw0E4-8mjGl3wVA,Crossfit Terminus,1046 Memorial Dr SE,Atlanta,GA,30316,33.747027,-84.353424,4.0,14,1,"{'GoodForKids': 'False', 'BusinessParking': '{...","Gyms, Active Life, Interval Training Gyms, Fit...","{'Monday': '16:0-19:0', 'Tuesday': '16:0-19:0'..."

In [10]:
business_df.describe()

,latitude,longitude,stars,review_count,is_open
count,160470.000000,160470.000000,160470.000000,160470.000000,160470.000000
mean,38.759436,-94.267912,3.658005,51.996367,0.767421
std,7.138593,19.975121,0.942648,130.071540,0.422478
min,27.998972,-123.393929,1.000000,5.000000,0.000000
25%,30.355886,-122.589599,3.000000,8.000000,1.000000
50%,42.177228,-84.383281,4.000000,17.000000,1.000000
75%,45.458672,-81.288724,4.500000,44.000000,1.000000
max,49.490000,71.113271,5.000000,9185.000000,1.000000

In [11]:
ga_df = business_df[(business_df['state'] == "GA")]
ga_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
4,PE9uqAjdw0E4-8mjGl3wVA,Crossfit Terminus,1046 Memorial Dr SE,Atlanta,GA,30316,33.747027,-84.353424,4.0,14,1,"{'GoodForKids': 'False', 'BusinessParking': '{...","Gyms, Active Life, Interval Training Gyms, Fit...","{'Monday': '16:0-19:0', 'Tuesday': '16:0-19:0'..."
15,g7CEhqBIpwTg6ERcMkCmrQ,Finish Line Car Wash,5510 Memorial Dr,Stone Mountain,GA,30083,33.800687,-84.212820,2.5,11,1,{'BusinessAcceptsCreditCards': 'True'},"Oil Change Stations, Smog Check Stations, Auto...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ..."
25,Y2ojrodkbEheGttZF8wYEQ,Wolf Camera and Image,3141 Piedmont Rd NE,Atlanta,GA,30305,33.842808,-84.370455,3.5,15,0,"{'BusinessParking': '{'garage': False, 'street...","Shopping, Photography Stores & Services","{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'..."
28,arEXRZYu8220bFBJ3VAh3A,Blake's On The Park,227 10th St NE,Atlanta,GA,30309,33.781475,-84.379955,3.5,170,1,"{'Alcohol': ''full_bar'', 'BusinessParking': '...","Nightlife, Bars, Gay Bars, Sports Bars","{'Monday': '15:0-3:0', 'Tuesday': '15:0-3:0', ..."
40,OmdMTKZe3j4oUkDrpru9VA,"Pickens, Jewelers",480 E Paces Ferry Rd NE,Atlanta,GA,30305,33.838656,-84.372192,4.0,9,1,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Local Services, Shopping, Jewelry, Jewelry Rep...","{'Monday': '0:0-0:0', 'Tuesday': '9:0-17:0', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160499,P6VbBg5uNhAaANcpwm2cVQ,Moe's Southwest Grill,863 Ponce De Leon Ave,Atlanta,GA,30306,33.773536,-84.359011,2.5,53,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Restaurants, Mexican, Tex-Mex","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
160522,OF1RGkYOeT2xxoi_Xnec7w,Emeril's Atlanta,"3500 Lenox Rd NE, Ste 100",Atlanta,GA,30326,33.852144,-84.365957,3.0,9,0,"{'RestaurantsAttire': ''dressy'', 'GoodForKids...","American (New), Restaurants, Cajun/Creole","{'Monday': '18:0-22:0', 'Tuesday': '18:0-22:0'..."
160536,zbpHTj_CztQBVVdNV3VPzw,Bubbles Salon,1579 Monroe Dr NE,Atlanta,GA,30324,33.798051,-84.369225,4.0,33,0,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Beauty & Spas, Hair Salons","{'Tuesday': '10:0-19:0', 'Wednesday': '10:0-19..."
160538,b7VmX7kKwe62MiXK-C_uJA,The Point at Westside Apartments,370 Northside Dr NW,Atlanta,GA,30318,33.765081,-84.404720,1.5,10,1,"{'ByAppointmentOnly': 'False', 'BusinessAccept...","Apartments, Real Estate, Home Services","{'Monday': '9:0-18:0', 'Tuesday': '9:0-18:0', ..."
160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': 'u'no'', 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [12]:
ga_df.categories.str.contains('Restaurant')

4         False
15        False
25        False
28        False
40        False
          ...
160499     True
160522     True
160536    False
160538    False
160575     True
Name: categories, Length: 18079, dtype: bool

In [13]:
restaurant_df=ga_df.loc[ga_df.categories.str.contains('Restaurant')]
restaurant_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': '{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
105,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340,33.896640,-84.280918,3.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Business...","Restaurants, Chinese",None
147,bP6goJODwRnM3AVy45Kn9w,Papi's Cuban & Caribbean Grill,216 Ponce De Leon Ave NE,Atlanta,GA,30308,33.772758,-84.380375,4.0,1001,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Caribbean, Cuban, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
155,yCeENvVAGQQ0PeeWU0Pl2g,Nature's Table Bistro,"6000 N Terminal Pkwy, Concourse E Centrepoint,...",Atlanta,GA,30320,33.640879,-84.425514,3.5,150,1,"{'BikeParking': 'False', 'WiFi': 'u'free'', 'R...","Restaurants, Sandwiches, Fast Food, American (...","{'Monday': '6:0-22:0', 'Tuesday': '6:0-22:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160375,fyBLsgCl04kzDyDvvntsig,Marco's Pita,752 Ponce De Leon Ave NE,Atlanta,GA,30306,33.774230,-84.362535,3.5,46,0,"{'RestaurantsPriceRange2': '1', 'RestaurantsRe...","Restaurants, Greek","{'Monday': '12:0-20:0', 'Tuesday': '12:0-20:0'..."
160390,N7luSQX9HJIYJzIdqzIEng,Vickery's Bar & Grill,1106 Crescent Ave NE,Atlanta,GA,30309,33.785008,-84.384517,3.5,47,0,"{'OutdoorSeating': 'True', 'RestaurantsReserva...","American (New), Southern, Restaurants","{'Monday': '11:30-2:0', 'Tuesday': '11:30-2:0'..."
160499,P6VbBg5uNhAaANcpwm2cVQ,Moe's Southwest Grill,863 Ponce De Leon Ave,Atlanta,GA,30306,33.773536,-84.359011,2.5,53,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Restaurants, Mexican, Tex-Mex","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
160522,OF1RGkYOeT2xxoi_Xnec7w,Emeril's Atlanta,"3500 Lenox Rd NE, Ste 100",Atlanta,GA,30326,33.852144,-84.365957,3.0,9,0,"{'RestaurantsAttire': ''dressy'', 'GoodForKids...","American (New), Restaurants, Cajun/Creole","{'Monday': '18:0-22:0', 'Tuesday': '18:0-22:0'..."
160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': 'u'no'', 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [14]:
atl_restaurants_df = restaurant_df[(restaurant_df['postal_code'] == '30002') | (restaurant_df['postal_code'] == '30030') | (restaurant_df['postal_code'] == '30032') |
                                   (restaurant_df['postal_code'] == '30033') | (restaurant_df['postal_code'] == '30067') | (restaurant_df['postal_code'] == '30079') |
                                   (restaurant_df['postal_code'] == '30080') | (restaurant_df['postal_code'] == '30084') | (restaurant_df['postal_code'] == '30303') |
                                   (restaurant_df['postal_code'] == '30305') | (restaurant_df['postal_code'] == '30306') | (restaurant_df['postal_code'] == '30307') |
                                   (restaurant_df['postal_code'] == '30308') | (restaurant_df['postal_code'] == '30309') | (restaurant_df['postal_code'] == '30310') |
                                   (restaurant_df['postal_code'] == '30311') | (restaurant_df['postal_code'] == '30312') | (restaurant_df['postal_code'] == '30313') |
                                   (restaurant_df['postal_code'] == '30314') | (restaurant_df['postal_code'] == '30315') | (restaurant_df['postal_code'] == '30316') |
                                   (restaurant_df['postal_code'] == '30317') | (restaurant_df['postal_code'] == '30318') | (restaurant_df['postal_code'] == '30319') |
                                   (restaurant_df['postal_code'] == '30324') | (restaurant_df['postal_code'] == '30326') | (restaurant_df['postal_code'] == '30327') |
                                   (restaurant_df['postal_code'] == '30328') | (restaurant_df['postal_code'] == '30329') | (restaurant_df['postal_code'] == '30337') |
                                   (restaurant_df['postal_code'] == '30338') | (restaurant_df['postal_code'] == '30339') | (restaurant_df['postal_code'] == '30340') |
                                   (restaurant_df['postal_code'] == '30341') | (restaurant_df['postal_code'] == '30342') | (restaurant_df['postal_code'] == '30344') |
                                   (restaurant_df['postal_code'] == '30345') | (restaurant_df['postal_code'] == '30346') | (restaurant_df['postal_code'] == '30354') |
                                   (restaurant_df['postal_code'] == '30360') | (
    restaurant_df['postal_code'] == '30363')
]

In [37]:
atl_restaurants_df

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
1,86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
2,105,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340,33.896641,-84.280918,3.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Business...","Restaurants, Chinese",NaN
3,147,bP6goJODwRnM3AVy45Kn9w,Papi's Cuban & Caribbean Grill,216 Ponce De Leon Ave NE,Atlanta,GA,30308,33.772758,-84.380375,4.0,1001,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Caribbean, Cuban, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
4,165,xSLdQjPgMhBrNIEtUgdWUA,Colossus Pizza,4369 Hugh Howell Rd,Tucker,GA,30084,33.850775,-84.209299,4.0,58,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Nightlife, Pizza, Sandwiches, Mediterranean, G...","{'Tuesday': '11:30-21:0', 'Wednesday': '11:30-..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5481,160375,fyBLsgCl04kzDyDvvntsig,Marco's Pita,752 Ponce De Leon Ave NE,Atlanta,GA,30306,33.774230,-84.362535,3.5,46,0,"{'RestaurantsPriceRange2': '1', 'RestaurantsRe...","Restaurants, Greek","{'Monday': '12:0-20:0', 'Tuesday': '12:0-20:0'..."
5482,160390,N7luSQX9HJIYJzIdqzIEng,Vickery's Bar & Grill,1106 Crescent Ave NE,Atlanta,GA,30309,33.785008,-84.384517,3.5,47,0,"{'OutdoorSeating': 'True', 'RestaurantsReserva...","American (New), Southern, Restaurants","{'Monday': '11:30-2:0', 'Tuesday': '11:30-2:0'..."
5483,160499,P6VbBg5uNhAaANcpwm2cVQ,Moe's Southwest Grill,863 Ponce De Leon Ave,Atlanta,GA,30306,33.773536,-84.359011,2.5,53,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Restaurants, Mexican, Tex-Mex","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
5484,160522,OF1RGkYOeT2xxoi_Xnec7w,Emeril's Atlanta,"3500 Lenox Rd NE, Ste 100",Atlanta,GA,30326,33.852144,-84.365957,3.0,9,0,"{'RestaurantsAttire': ""'dressy'"", 'GoodForKids...","American (New), Restaurants, Cajun/Creole","{'Monday': '18:0-22:0', 'Tuesday': '18:0-22:0'..."
5485,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': ""u'no'"", 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [39]:
atl_restaurants_df.reset_index(drop=True).drop(['Unnamed: 0'], axis=1)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
1,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
2,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340,33.896641,-84.280918,3.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Business...","Restaurants, Chinese",NaN
3,bP6goJODwRnM3AVy45Kn9w,Papi's Cuban & Caribbean Grill,216 Ponce De Leon Ave NE,Atlanta,GA,30308,33.772758,-84.380375,4.0,1001,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Caribbean, Cuban, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
4,xSLdQjPgMhBrNIEtUgdWUA,Colossus Pizza,4369 Hugh Howell Rd,Tucker,GA,30084,33.850775,-84.209299,4.0,58,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Nightlife, Pizza, Sandwiches, Mediterranean, G...","{'Tuesday': '11:30-21:0', 'Wednesday': '11:30-..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4888,fyBLsgCl04kzDyDvvntsig,Marco's Pita,752 Ponce De Leon Ave NE,Atlanta,GA,30306,33.774230,-84.362535,3.5,46,0,"{'RestaurantsPriceRange2': '1', 'RestaurantsRe...","Restaurants, Greek","{'Monday': '12:0-20:0', 'Tuesday': '12:0-20:0'..."
4889,N7luSQX9HJIYJzIdqzIEng,Vickery's Bar & Grill,1106 Crescent Ave NE,Atlanta,GA,30309,33.785008,-84.384517,3.5,47,0,"{'OutdoorSeating': 'True', 'RestaurantsReserva...","American (New), Southern, Restaurants","{'Monday': '11:30-2:0', 'Tuesday': '11:30-2:0'..."
4890,P6VbBg5uNhAaANcpwm2cVQ,Moe's Southwest Grill,863 Ponce De Leon Ave,Atlanta,GA,30306,33.773536,-84.359011,2.5,53,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Restaurants, Mexican, Tex-Mex","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
4891,OF1RGkYOeT2xxoi_Xnec7w,Emeril's Atlanta,"3500 Lenox Rd NE, Ste 100",Atlanta,GA,30326,33.852144,-84.365957,3.0,9,0,"{'RestaurantsAttire': ""'dressy'"", 'GoodForKids...","American (New), Restaurants, Cajun/Creole","{'Monday': '18:0-22:0', 'Tuesday': '18:0-22:0'..."
4892,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': ""u'no'"", 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [ ]:
# atl_restaurants_df = business_df.drop(['Unnamed: 0'], axis=1)
# atl_restaurants_df.head(2)

In [44]:
atl_restaurants_df.to_json("yelp_atl_restaurants.json")

In [45]:
atl_restaurants_df.to_csv("yelp_atl_restaurants_csv.csv")

### Read CSV back in to further clean data

In [46]:
atl_restaurants_df = pd.read_csv("yelp_atl_restaurants_csv.csv")

In [47]:
categories_col_list = []
for index, row in atl_restaurants_df.iterrows():
    categories_col_list.append(row["categories"])

In [48]:
categories_dict = {}

for categories in categories_col_list:
    cat_list = categories.split(", ")
    for item in cat_list:
        if categories_dict.get(item, False):
            categories_dict[item] += 1
        else:
            categories_dict[item] = 1
            
remove_list = ["Restaurants","Food","Bars","Nightlife","Event Planning & Services","Coffee & Tea",
               "Caterers","Desserts","Cocktail Bars","Lounges","Wine Bars","Wine & Spirits","Beer",
               "Sports Bars", "Ice Cream & Frozen Yogurt", "Venues & Event Spaces", "Hookah Bars",
               "Beer Bar", "Shopping", "Food Delivery Services", "Food Stands", "Gluten-Free", "Arts & Entertainment",
               'Juice Bars & Smoothies', "Grocery", "Food Court", "Automotive", "Convenience Stores",
               "Dance Clubs", "Breweries", "Local Flavor", "Bubble Tea", "Dive Bars"]

for item in remove_list:
    categories_dict.pop(item)
            
new_categories = []

for key, value in categories_dict.items():
    if value > 60:
        new_categories.append(key)
        
new_categories

['Sandwiches',
 'Bakeries',
 'Chinese',
 'Caribbean',
 'Pizza',
 'Mediterranean',
 'Greek',
 'Italian',
 'Southern',
 'Mexican',
 'Tex-Mex',
 'Fast Food',
 'Latin American',
 'Tapas Bars',
 'American (New)',
 'Barbeque',
 'Burgers',
 'Vietnamese',
 'Steakhouses',
 'Pubs',
 'American (Traditional)',
 'Japanese',
 'Specialty Food',
 'Thai',
 'Sushi Bars',
 'Middle Eastern',
 'Korean',
 'Soul Food',
 'Delis',
 'Chicken Wings',
 'Tacos',
 'Indian',
 'Vegetarian',
 'Seafood',
 'Hot Dogs',
 'Cafes',
 'Asian Fusion',
 'Comfort Food',
 'Vegan',
 'Breakfast & Brunch',
 'Food Trucks',
 'Cajun/Creole',
 'Salad',
 'Diners',
 'French',
 'Soup',
 'Tapas/Small Plates',
 'Gastropubs',
 'Chicken Shop']

In [50]:
categories_df = pd.DataFrame({"Category": new_categories})
# categories_df.to_csv("../categories.csv")
categories_df.to_json("../categories.json")

In [30]:
search_string = ""

for index, cat in enumerate(new_categories):
    if index == 0:
        search_string = cat
    else:
        search_string += f"|{cat}"
    
atl_restaurants_df["include"] = atl_restaurants_df["categories"].str.contains(search_string, regex=True)
atl_restaurants_df = atl_restaurants_df.loc[atl_restaurants_df["include"] == True, :]
del atl_restaurants_df["include"]
atl_restaurants_df

C:\Users\Sharon\anaconda3\envs\PythonData\lib\site-packages\pandas\core\strings.py:1954: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,62,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326,33.846335,-84.363578,3.0,11,1,"{'RestaurantsGoodForGroups': 'False', 'GoodFor...","Food, Restaurants, Cheesesteaks, Sandwiches, J...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
1,86,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305,33.842875,-84.378539,4.0,231,1,"{'BikeParking': 'True', 'BusinessParking': ""{'...","Restaurants, Patisserie/Cake Shop, Desserts, F...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
2,105,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340,33.896641,-84.280918,3.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Business...","Restaurants, Chinese",NaN
3,147,bP6goJODwRnM3AVy45Kn9w,Papi's Cuban & Caribbean Grill,216 Ponce De Leon Ave NE,Atlanta,GA,30308,33.772758,-84.380375,4.0,1001,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Caribbean, Cuban, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
4,165,xSLdQjPgMhBrNIEtUgdWUA,Colossus Pizza,4369 Hugh Howell Rd,Tucker,GA,30084,33.850775,-84.209299,4.0,58,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Nightlife, Pizza, Sandwiches, Mediterranean, G...","{'Tuesday': '11:30-21:0', 'Wednesday': '11:30-..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5481,160375,fyBLsgCl04kzDyDvvntsig,Marco's Pita,752 Ponce De Leon Ave NE,Atlanta,GA,30306,33.774230,-84.362535,3.5,46,0,"{'RestaurantsPriceRange2': '1', 'RestaurantsRe...","Restaurants, Greek","{'Monday': '12:0-20:0', 'Tuesday': '12:0-20:0'..."
5482,160390,N7luSQX9HJIYJzIdqzIEng,Vickery's Bar & Grill,1106 Crescent Ave NE,Atlanta,GA,30309,33.785008,-84.384517,3.5,47,0,"{'OutdoorSeating': 'True', 'RestaurantsReserva...","American (New), Southern, Restaurants","{'Monday': '11:30-2:0', 'Tuesday': '11:30-2:0'..."
5483,160499,P6VbBg5uNhAaANcpwm2cVQ,Moe's Southwest Grill,863 Ponce De Leon Ave,Atlanta,GA,30306,33.773536,-84.359011,2.5,53,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Restaurants, Mexican, Tex-Mex","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
5484,160522,OF1RGkYOeT2xxoi_Xnec7w,Emeril's Atlanta,"3500 Lenox Rd NE, Ste 100",Atlanta,GA,30326,33.852144,-84.365957,3.0,9,0,"{'RestaurantsAttire': ""'dressy'"", 'GoodForKids...","American (New), Restaurants, Cajun/Creole","{'Monday': '18:0-22:0', 'Tuesday': '18:0-22:0'..."
5485,160575,uXdQkuEtvLAzfc3MsO-sTQ,Mama's Cocina Latina,1958 Piedmont Rd NE,Atlanta,GA,30324,33.810996,-84.367084,3.0,185,1,"{'WiFi': ""u'no'"", 'BusinessAcceptsCreditCards'...","Restaurants, Mexican, Latin American","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [31]:
atl_restaurants_df.to_json("yelp_atl_restaurants.json")

In [32]:
atl_restaurants_df.to_csv("yelp_atl_restaurants_csv.csv")